#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace Caustics { struct FCaustics; }

namespace Wave_3 { struct FWave_3; }

namespace CartelCharacterTooltip_0 { class UCartelCharacterTooltip_C; }

namespace OponentAnim_Militia { struct FAnimBlueprintGeneratedConstantData; }

namespace Foam_Generator_0 { struct FFoam_Generator; }

namespace OponentAnim_KiraWalking { struct FAnimBlueprintGeneratedConstantData; }

namespace Underwater { struct FUnderwater; }

namespace CartelCharacterTooltip { class UCartelCharacterTooltip_C; }

namespace Global_Displacement_0 { struct FGlobal_Displacement; }

namespace GodRays_0 { struct FGodRays; }

namespace Wave_2_0 { struct FWave_2; }

namespace BroJam_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Wave_4_0 { struct FWave_4; }

namespace BaseOffset_0 { struct FBaseOffset; }

namespace OponentAnim_Policeman { struct FAnimBlueprintGeneratedConstantData; }

namespace Refraction_0 { struct FRefraction; }

namespace Wave_2 { struct FWave_2; }

namespace OponentAnim_TIMMY { struct FAnimBlueprintGeneratedConstantData; }

namespace RaidHelicopter_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace GodRays { struct FGodRays; }

namespace Global_Displacement { struct FGlobal_Displacement; }

namespace BaseOffset { struct FBaseOffset; }

namespace WorkerSpotAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Wave_1_0 { struct FWave_1; }

namespace BaseNPC_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Wave_1 { struct FWave_1; }

namespace OponentAnim_Thug { struct FAnimBlueprintGeneratedConstantData; }

namespace PrisonerAnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Foam_Generator { struct FFoam_Generator; }

namespace Refraction { struct FRefraction; }

namespace Wave_4 { struct FWave_4; }

namespace Caustics_0 { struct FCaustics; }

namespace Surface_Light_0 { struct FSurface_Light; }

namespace Underwater_0 { struct FUnderwater; }

namespace Wave_3_0 { struct FWave_3; }

namespace Surface_Light { struct FSurface_Light; }


namespace OponentAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace PlayerCharacter_FPBody_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace PlayerCharacter_AnimBP_UE5
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
